#config_version=6
mode_settings:
    display_delay_ms: 2000
    bonus_entries:
    - event: bonus_caps
      score: (current_player.slurm_caps_total * 25 * current_player.fry_multiplier)
    - event: bonus_hypnotoad_saves
      score: (current_player.hypnotoad_saves * 250)
    - event: bonus_dark_matter
      score: (current_player.dark_matter * 200 * (1 + current_player.nibbler_level))

slides:
    bonus_start_slide:
        widgets:
            - type: text
              text: BONUS
              font_size: 60
              color: black
              y: 672
              x: 1170
              anchor_x: left
              anchor_y: bottom
            - type: image
              image: bonus_blank
    slurm_bonus:
        widgets:
            - type: text
              text: Slurm Caps
              font_size: 60
              color: black
              y: 774
              x: 1370
              anchor_x: left
              anchor_y: bottom
            - type: text
              text: (score)
              font_size: 50
              color: black
              y: 674
              x: 1370
              anchor_x: left
              anchor_y: bottom
            - type: image
              image: bonus_slurm_slide
    hypnotoad_bonus:
        widgets:
            - type: text
              text: Toad Bonus
              font_size: 60
              color: black
              y: 774
              x: 1370
              anchor_x: left
              anchor_y: bottom
            - type: text
              text: (score)
              font_size: 50
              color: black
              y: 674
              x: 1370
              anchor_x: left
              anchor_y: bottom
            - type: image
              image: bonus_hypnotoad_slide
    dark_matter_bonus:
        widgets:
            - type: text
              text: Dark Matter
              font_size: 60
              color: black
              y: 774
              x: 1370
              anchor_x: left
              anchor_y: bottom
            - type: text
              text: (score)
              font_size: 50
              color: black
              y: 674
              x: 1370
              anchor_x: left
              anchor_y: bottom
            - type: image
              image: bonus_dark_matter_slide
    bonus_multiplier_slide:
        widgets:
            - type: text
              text: Multiplier
              font_size: 60
              color: black
              y: 672
              x: 1170
              anchor_x: left
              anchor_y: bottom
            - type: text
              text: (player|bonus_multiplier)x
              font_size: 60
              color: black
              y: 572
              x: 1170
              anchor_x: left
              anchor_y: bottom
            - type: video
              video: bonus_multiplier_clip
    bonus_total_slide:
        widgets:
            - type: text
              text: TOTAL BONUS
              font_size: 60
              color: black
              y: 672
              x: 1170
              anchor_x: left
              anchor_y: bottom
            - type: text
              text: (score)
              font_size: 60
              color: black
              y: 572
              x: 1170
              anchor_x: left
              anchor_y: bottom
            - type: image
              image: bonus_blank

slide_player:
    mode_bonus_started:
        bonus_start_slide:
            target: display1
            force: true
    bonus_caps:
        slurm_bonus:
            target: display1
    bonus_hypnotoad_saves:
        hypnotoad_bonus:
            target: display1
    bonus_dark_matter:
        dark_matter_bonus:
            target: display1
    bonus_subtotal:
        bonus_multiplier_slide:
            target: display1
    bonus_total:
        bonus_total_slide:
            target: display1
